apiVersion: v1
kind: Service
metadata:
  name: studentmarkservice-service
  namespace: studentmarkservice-ns
spec:
  type: NodePort
  selector:
    app: studentmarkservice
  ports:
    - port: 8100          # Service port (inside cluster)
      targetPort: 8100    # Container port
      nodePort: 30081     # Port accessible from Postman (your host)
